name: Python Coverage

on:
  pull_request:
    branches:
      - main

jobs:
  python-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install coverage==7.9.1
          pip freeze

      - name: Run tests with coverage
        id: coverage
        run: |
          coverage run -m unittest discover -s tests -p "*_test.py"
          echo "coverage_report<<EOF" >> $GITHUB_OUTPUT
          coverage report >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Generate coverage reports
        run: |
          coverage xml
          coverage html

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            coverage.xml
            htmlcov/

      - name: Post coverage comment
        uses: actions/github-script@v7
        with:
          script: |
            const artifactsUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;
            
            const commentBody = `### Test Coverage Report
            <details>
            <summary>Coverage Details</summary>

            \`\`\`
            ${steps.coverage.outputs.coverage_report}
            \`\`\`

            </details>

            [📊 Detailed HTML Coverage Report](${artifactsUrl})
            `;

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: commentBody
            });
